const products = [
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
    {name:"tacno camon 11", price:2500,image: "./images/pic (1).jpg"},
]

